version: '3'

services:
  db_auditoria:
    container_name: db_auditoria
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_auditoria
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local